name: SurfDock
channels:
  - mx
  - pyg
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aiohttp=3.9.3=py310h2372a71_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - ambertools=22.5=py310hd182041_0
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - archspec=0.2.3=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h2372a71_4
  - arpack=3.7.0=hdefa2d7_2
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - babel=2.13.1=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - biopandas=0.4.1=pyhd8ed1ab_1
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.5=hc2324a3_1
  - boltons=24.0.0=pyhd8ed1ab_0
  - boost=1.78.0=py310hcb52e73_5
  - boost-cpp=1.78.0=h2c5509c_4
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bson=0.5.9=py_0
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - c-blosc2=2.14.4=hb4ffafa_1
  - ca-certificates=2024.8.30=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=pyhd8ed1ab_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=24.5.0=py310h06a4308_0
  - conda-libmamba-solver=24.1.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - contourpy=1.2.1=py310hd41b1e2_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cycler=0.12.1=pyhd8ed1ab_0
  - cython=3.0.10=py310hc6cd4ac_0
  - debugpy=1.8.1=py310hc6cd4ac_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hc118613_108
  - filelock=3.13.4=pyhd8ed1ab_0
  - fmt=10.2.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py310h2372a71_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - frozendict=2.4.2=py310h5eee18b_0
  - frozenlist=1.4.1=py310h2372a71_0
  - fsspec=2024.3.1=pyhca7485f_0
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.2=py310h3ec546c_1
  - gnutls=3.6.13=h85f3911_1
  - greenlet=3.0.3=py310hc6cd4ac_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.14.3=nompi_h4f84152_100
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.22.2=pyh707e725_0
  - ipywidgets=8.1.2=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.4.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json5=0.9.24=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hff52083_3
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.21.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hff52083_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.26.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.10=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.2=h2aa1ff5_1
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.7.1=hca28451_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.80.0=hf2295e7_4
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libmamba=1.5.8=had39da4_0
  - libmambapy=1.5.8=py310h39ff949_0
  - libnetcdf=4.9.2=nompi_h9612171_113
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.43=h2797004_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.28=hfc55251_2
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.3.0=h0fcbabc_4
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_1
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.6=h232c23b_1
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.2.13=hd590300_5
  - lightning-utilities=0.11.2=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - loguru=0.7.2=py310hff52083_2
  - lxml=5.1.0=py310hcfd0673_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - mamba=1.5.8=py310h51d5547_0
  - markupsafe=2.1.5=py310h2372a71_0
  - matplotlib-base=3.8.4=py310h62c0568_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_0
  - mdtraj=1.9.9=py310h523e8d7_1
  - menuinst=2.0.2=py310hff52083_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_1
  - mpmath=1.3.0=pyhd8ed1ab_0
  - multidict=6.0.5=py310h2372a71_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.3=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - netcdf-fortran=4.6.1=nompi_hacb5139_103
  - nettle=3.6=he412f7d_0
  - networkx=3.2=pyhd8ed1ab_0
  - notebook=7.1.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - ocl-icd=2.3.2=hd590300_1
  - ocl-icd-system=1.0.0=1
  - olefile=0.47=pyhd8ed1ab_0
  - openbabel=3.1.1=py310hbff9852_9
  - openff-amber-ff-ports=0.0.4=pyhca7485f_0
  - openff-forcefields=2024.03.0=pyhca7485f_0
  - openff-interchange=0.3.25=pyhd8ed1ab_1
  - openff-interchange-base=0.3.25=pyhd8ed1ab_1
  - openff-models=0.1.2=pyhca7485f_0
  - openff-toolkit=0.15.2=pyhd8ed1ab_0
  - openff-toolkit-base=0.15.2=pyhd8ed1ab_0
  - openff-units=0.2.2=pyhca7485f_0
  - openff-utilities=0.1.12=pyhd8ed1ab_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=h7d73246_0
  - openmm=8.1.1=py310h43b6314_1
  - openmmforcefields=0.12.0=pyhd8ed1ab_0
  - openssl=3.4.0=hb9d3cd8_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - packmol=20.010=h86c2bf4_0
  - pandas=2.1.2=py310hcc13569_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panedr=0.8.0=pyhd8ed1ab_0
  - parmed=4.2.2=py310hc6cd4ac_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pdbfixer=1.9=pyh1a96a4e_0
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py310h07f4688_0
  - pint=0.23=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - plyfile=1.0.1=pyhd8ed1ab_0
  - prody=2.4.0=py310heca2aa9_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py310h2372a71_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-cpuinfo=9.0.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycairo=1.26.0=py310hda9f760_0
  - pycosat=0.6.6=py310h2372a71_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.7.0=pyhd8ed1ab_0
  - pydantic-core=2.18.1=py310hcb5633a_0
  - pyedr=0.8.0=pyhd8ed1ab_0
  - pyg=2.5.2=py310_torch_2.2.0_cu121
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.9.2=py310hd76cd5d_2
  - python=3.10.0=h543edf9_3_cpython
  - python-constraint=1.4.0=py_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytorch=2.2.2=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - pyzmq=25.1.2=py310h795f18f_0
  - readline=8.2=h8228510_1
  - reduce=3.24=0
  - referencing=0.34.0=pyhd8ed1ab_0
  - reportlab=3.5.68=py310h94fcab3_1
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.18.0=py310hcb5633a_0
  - ruamel.yaml=0.18.6=py310h2372a71_0
  - ruamel.yaml.clib=0.2.8=py310h2372a71_0
  - scipy=1.8.1=py310hdfbd76f_2
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smirnoff99frosst=1.1.0=pyh44b312d_0
  - snappy=1.2.0=hdb0a2a9_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.29=py310h2372a71_0
  - sqlite=3.45.2=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.11.0=h00ab1b0_1
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.4.0=pyhc1e730c_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tinydb=4.8.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - torch-ema=0.3=pyhd8ed1ab_0
  - torchaudio=2.2.2=py310_cu121
  - torchmetrics=1.2.1=pyhd8ed1ab_0
  - torchtriton=2.2.0=py310
  - torchvision=0.17.2=py310_cu121
  - tornado=6.4=py310h2372a71_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.11.0=hd8ed1ab_0
  - typing_extensions=4.11.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - validators=0.28.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.10=pyhd8ed1ab_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.8.0=h59595ed_0
  - yarl=1.9.4=py310h2372a71_0
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstandard=0.22.0=py310h1275a96_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - accelerate==0.15.0
      - amberlite==22.0
      - amberutils==21.0
      - appdirs==1.4.4
      - biopython==1.79
      - click==8.1.7
      - dimorphite-dl==1.3.2
      - docker-pycreds==0.4.0
      - e3nn==0.5.1
      - et-xmlfile==1.1.0
      - fair-esm==2.0.1
      - fasteners==0.19
      - gitdb==4.0.11
      - gitpython==3.1.43
      - griddataformats==1.0.2
      - gsd==3.2.1
      - huggingface-hub==0.17.3
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - mdanalysis==2.4.0
      - mmpbsa-py==16.0
      - mmtf-python==1.1.3
      - mrcfile==1.5.0
      - msgpack==1.0.8
      - numexpr==2.10.0
      - numpy==1.24.4
      - openpyxl==3.1.3
      - opt-einsum==3.3.0
      - opt-einsum-fx==0.1.4
      - packmol-memgen==1.2.3rc0
      - pdb4amber==22.0
      - posebusters==0.2.13
      - prefetch-generator==1.0.3
      - protobuf==4.25.3
      - pyg-lib==0.4.0+pt22cu121
      - pymesh==1.0.2
      - pymesh2==0.3.1
      - pympler==1.0.1
      - pytraj==2.0.6
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rdkit==2023.3.1
      - rdkit-pypi==2022.9.5
      - regex==2023.12.25
      - sander==22.0
      - scikit-learn==1.3.2
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - spyrmsd==0.7.0
      - tokenizers==0.13.3
      - torch-cluster==1.6.3+pt22cu121
      - torch-scatter==2.1.2+pt22cu121
      - torch-sparse==0.6.18+pt22cu121
      - torch-spline-conv==1.2.2+pt22cu121
      - transformers==4.29.2
      - wandb==0.16.1
